import io

path = "Data/raw/fifa_world_cup_2026_golden_dataset.csv"

with io.open(path, encoding="utf-8") as f:
    lines = f.readlines()

# Country name fixes (apply to all matching lines)
COUNTRY_FIXES = [
    ("C?te d'Ivoire", "Côte d'Ivoire"),
    ("Cura?ao", "Curaçao"),
    ("T?rkiye", "Türkiye"),
]

# Per-line player name fixes: 1-based line number -> (old, new)
NAME_FIXES = {
    3: ("Maxime Cr?peau", "Maxime Crépeau"),
    13: ("Isma?l Kon?", "Ismaël Koné"),
    16: ("Mathieu Choini?re", "Mathieu Choinière"),
    28: ("Ra?l Rangel", "Raúl Rangel"),
    31: ("Jes?s Gallardo", "Jesús Gallardo"),
    32: ("?rik Lira", "Érik Lira"),
    35: ("Brian Guti?rrez", "Brian Gutiérrez"),
    38: ("Armando Gonz?lez", "Armando González"),
    39: ("Guillermo Mart?nez", "Guillermo Martínez"),
    57: ("Cristian Rold?n", "Cristian Roldán"),
    91: ("Deni Juri?", "Deni Jurić"),
    251: ("Edm?lson Junior", "Edmílson Junior"),
    306: ("Anthony Mandr?a", "Anthony Mandréa"),
    310: ("Sohaib Na?r", "Sohaib Naïr"),
    312: ("A?ssa Mandi", "Aïssa Mandi"),
    314: ("Rayan A?t-Nouri", "Rayan Aït-Nouri"),
    321: ("Far?s Cha?bi", "Farès Chaïbi"),
    326: ("Far?s Ghedjemis", "Farès Ghedjemis"),
    349: ("Nathana?l Mbuku", "Nathanaël Mbuku"),
    351: ("Th?o Bongonda", "Théo Bongonda"),
    356: ("C?dric Bakambu", "Cédric Bakambu"),
    359: ("Mohamed Kon?", "Mohamed Koné"),
    367: ("Gu?la Dou?", "Guéla Doué"),
    368: ("Ibrahim Sangar?", "Ibrahim Sangaré"),
    369: ("Jean Micha?l Seri", "Jean Michaël Seri"),
    370: ("Christ Inao Oula?", "Christ Inao Oulaï"),
    371: ("Franck Kessi?", "Franck Kessié"),
    373: ("Bazoumana Tour?", "Bazoumana Touré"),
    376: ("B?nie Traor?", "Bénie Traoré"),
    380: ("Nicolas P?p?", "Nicolas Pépé"),
    418: ("Derrick K?hn", "Derrick Köhn"),
    434: ("Ransford K?nigsd?rffer", "Ransford Königsdörffer"),
    444: ("Isma?l Baouf", "Ismaïl Baouf"),
    461: ("Brahim D?az", "Brahim Díaz"),
    470: ("Moussa Niakhat?", "Moussa Niakhaté"),
    482: ("Path? Ciss", "Pathé Ciss"),
    483: ("Kr?pin Diatta", "Krépin Diatta"),
    487: ("Isma?la Sarr", "Ismaïla Sarr"),
    536: ("Isma?l Gharbi", "Ismaël Gharbi"),
    552: ("Juri?n Gaari", "Jurriën Gaari"),
    566: ("Kenji Gorr?", "Kenji Gorré"),
    570: ("J?rgen Locadia", "Jürgen Locadia"),
    574: ("Josu? Duverger", "Josué Duverger"),
    576: ("Jean-K?vin Duverne", "Jean-Kévin Duverne"),
    577: ("Ricardo Ad?", "Ricardo Adé"),
    579: ("Martin Exp?rience", "Martin Expérience"),
    585: ("Carl Saint?", "Carl Sainté"),
    590: ("Josu? Casimir", "Josué Casimir"),
    596: ("Yassin Fortun?", "Yassin Fortuné"),
    598: ("C?sar Samudio", "César Samudio"),
    599: ("Luis Mej?a", "Luis Mejía"),
    600: ("Jos? C?rdoba", "José Córdoba"),
    601: ("Andr?s Andrade", "Andrés Andrade"),
    604: ("Mart?n Krug", "Martín Krug"),
    605: ("Jorge Guti?rrez", "Jorge Gutiérrez"),
    606: ("?ric Davis", "Éric Davis"),
    608: ("C?sar Blackman", "César Blackman"),
    609: ("Cristian Mart?nez", "Cristian Martínez"),
    611: ("An?bal Godoy", "Aníbal Godoy"),
    613: ("Jos? Luis Rodr?guez", "José Luis Rodríguez"),
    614: ("Ismael D?az", "Ismael Díaz"),
    615: ("Yoel B?rcenas", "Yoel Bárcenas"),
    616: ("C?sar Yanis", "César Yanis"),
    617: ("Kadir Barr?a", "Kadir Barría"),
    618: ("Jos? Fajardo", "José Fajardo"),
    620: ("Emiliano Mart?nez", "Emiliano Martínez"),
    621: ("Ger?nimo Rulli", "Gerónimo Rulli"),
    625: ("Tom?s Palacios", "Tomás Palacios"),
    626: ("Lucas Mart?nez Quarta", "Lucas Martínez Quarta"),
    627: ("Nicol?s Otamendi", "Nicolás Otamendi"),
    628: ("Nicol?s Tagliafico", "Nicolás Tagliafico"),
    630: ("Marcos Acu?a", "Marcos Acuña"),
    632: ("Agust?n Giay", "Agustín Giay"),
    633: ("M?ximo Perrone", "Máximo Perrone"),
    635: ("Enzo Fern?ndez", "Enzo Fernández"),
    637: ("Valent?n Barco", "Valentín Barco"),
    641: ("Nico Gonz?lez", "Nico González"),
    647: ("Juli?n Alvarez", "Julián Alvarez"),
    648: ("Jos? Manuel L?pez", "José Manuel López"),
    655: ("Roger Iba?ez", "Roger Ibañez"),
    656: ("L?o Pereira", "Léo Pereira"),
    669: ("Jo?o Pedro", "João Pedro"),
    673: ("?lvaro Montero", "Álvaro Montero"),
    676: ("Jhon Lucum?", "Jhon Lucumí"),
    677: ("Davinson S?nchez", "Davinson Sánchez"),
    682: ("Daniel Mu?oz", "Daniel Muñoz"),
    684: ("Richard R?os", "Richard Ríos"),
    686: ("Kevin Casta?o", "Kevin Castaño"),
    689: ("James Rodr?guez", "James Rodríguez"),
    691: ("Luis D?az", "Luis Díaz"),
    692: ("Andr?s G?mez", "Andrés Gómez"),
    693: ("J?minton Campaz", "Jáminton Campaz"),
    696: ("Luis Su?rez", "Luis Suárez"),
    697: ("Jhon C?rdoba", "Jhon Córdoba"),
    698: ("Rafael Borr?", "Rafael Borré"),
    700: ("Mois?s Ram?rez", "Moisés Ramírez"),
    702: ("Hern?n Gal?ndez", "Hernán Galíndez"),
    704: ("Piero Hincapi?", "Piero Hincapié"),
    705: ("Joel Ord??ez", "Joel Ordóñez"),
    706: ("L?o Realpe", "Léo Realpe"),
    708: ("F?lix Torres", "Félix Torres"),
    709: ("Pervis Estupi??n", "Pervis Estupiñán"),
    712: ("Jos? Andr?s Hurtado", "José Andrés Hurtado"),
    713: ("Mois?s Caicedo", "Moisés Caicedo"),
    714: ("Jordy Alc?var", "Jordy Alcívar"),
    717: ("Kendry P?ez", "Kendry Páez"),
    722: ("Bryan Ram?rez", "Bryan Ramírez"),
    723: ("El?as Legendre Qui??nez", "Elías Legendre Quiñónez"),
    727: ("Jeremy Ar?valo", "Jeremy Arévalo"),
    728: ("Kevin Rodr?guez", "Kevin Rodríguez"),
    732: ("Gast?n Olveira", "Gastón Olveira"),
    733: ("Roberto Fern?ndez", "Roberto Fernández"),
    735: ("Gustavo G?mez", "Gustavo Gómez"),
    736: ("J?nior Alonso", "Júnior Alonso"),
    737: ("Jos? Canale", "José Canale"),
    738: ("Fabi?n Balbuena", "Fabián Balbuena"),
    739: ("Gustavo Vel?zquez", "Gustavo Velázquez"),
    741: ("Juan Jos? C?ceres", "Juan José Cáceres"),
    742: ("Alan Ben?tez", "Alan Benítez"),
    745: ("Diego G?mez", "Diego Gómez"),
    746: ("Dami?n Bobadilla", "Damián Bobadilla"),
    747: ("Mat?as Galarza", "Matías Galarza"),
    751: ("Miguel Almir?n", "Miguel Almirón"),
    752: ("Ram?n Sosa", "Ramón Sosa"),
    753: ("?lex Arce", "Álex Arce"),
    755: ("Gabriel ?valos", "Gabriel Ávalos"),
    760: ("Jos? Mar?a Gim?nez", "José María Giménez"),
    762: ("Sebasti?n C?ceres", "Sebastián Cáceres"),
    763: ("Maxi Ara?jo", "Maxi Araújo"),
    764: ("Math?as Olivera", "Mathías Olivera"),
    765: ("Joaqu?n Piquerez", "Joaquín Piquerez"),
    767: ("Mat?as Vi?a", "Matías Viña"),
    768: ("Jos? Luis Rodr?guez", "José Luis Rodríguez"),
    771: ("Emiliano Mart?nez", "Emiliano Martínez"),
    772: ("Nicol?s Fonseca", "Nicolás Fonseca"),
    774: ("Nicol?s de la Cruz", "Nicolás de la Cruz"),
    776: ("Brian Rodr?guez", "Brian Rodríguez"),
    777: ("Agust?n Canobbio", "Agustín Canobbio"),
    780: ("Darwin N??ez", "Darwin Núñez"),
    781: ("Federico Vi?as", "Federico Viñas"),
    782: ("Agust?n ?lvarez", "Agustín Álvarez"),
    798: ("Marko Stameni?", "Marko Stamenić"),
    817: ("Maximilian W?ber", "Maximilian Wöber"),
    826: ("Alessandro Sch?pf", "Alessandro Schöpf"),
    855: ("J?r?my Doku", "Jérémy Doku"),
    857: ("Dodi Luk?bakio", "Dodi Lukébakio"),
    858: ("Lo?s Openda", "Loïs Openda"),
    866: ("Martin Erli?", "Martin Erlić"),
    872: ("Petar Su?i?", "Petar Sučić"),
    874: ("Mario Pa?ali?", "Mario Pašalić"),
    875: ("Luka Modri?", "Luka Modrić"),
    878: ("Nikola Vla?i?", "Nikola Vlašić"),
    881: ("Ivan Peri?i?", "Ivan Perišić"),
    882: ("Marco Pa?ali?", "Marco Pašalić"),
    891: ("Marc Gu?hi", "Marc Guéhi"),
    925: ("Ibrahima Konat?", "Ibrahima Konaté"),
    928: ("Theo Hern?ndez", "Theo Hernández"),
    929: ("Lucas Hern?ndez", "Lucas Hernández"),
    932: ("Aur?lien Tchouam?ni", "Aurélien Tchouaméni"),
    933: ("N'Golo Kant?", "N'Golo Kanté"),
    934: ("Warren Za?re-Emery", "Warren Zaïre-Emery"),
    939: ("D?sir? Dou?", "Désiré Doué"),
    941: ("Kylian Mbapp?", "Kylian Mbappé"),
    942: ("Ousmane Demb?l?", "Ousmane Dembélé"),
    943: ("Hugo Ekitik?", "Hugo Ekitiké"),
    946: ("Alexander N?bel", "Alexander Nübel"),
    953: ("Antonio R?diger", "Antonio Rüdiger"),
    961: ("Pascal Gro?", "Pascal Groß"),
    965: ("Chris F?hrich", "Chris Führich"),
    966: ("Leroy San?", "Leroy Sané"),
    977: ("Nathan Ak?", "Nathan Aké"),
    997: ("?rjan Nyland", "Ørjan Nyland"),
    1000: ("Torbj?rn Heggem", "Torbjørn Heggem"),
    1001: ("Leo ?stig?rd", "Leo Østigård"),
    1002: ("Odin Bj?rtuft", "Odin Bjørtuft"),
    1004: ("David M?ller Wolfe", "David Møller Wolfe"),
    1005: ("Fredrik Bj?rkan", "Fredrik Bjørkan"),
    1018: ("J?rgen Strand Larsen", "Jørgen Strand Larsen"),
    1019: ("Alexander S?rloth", "Alexander Sørloth"),
    1021: ("Jos? S?", "José Sá"),
    1023: ("Gon?alo In?cio", "Gonçalo Inácio"),
    1024: ("Tom?s Ara?jo", "Tomás Araújo"),
    1025: ("Ant?nio Silva", "António Silva"),
    1030: ("Jo?o Cancelo", "João Cancelo"),
    1032: ("R?ben Neves", "Rúben Neves"),
    1033: ("Sam? Costa", "Samú Costa"),
    1034: ("Jo?o Neves", "João Neves"),
    1037: ("Francisco Trinc?o", "Francisco Trincão"),
    1038: ("Pedro Gon?alves", "Pedro Gonçalves"),
    1040: ("Gon?alo Guedes", "Gonçalo Guedes"),
    1042: ("Francisco Concei??o", "Francisco Conceição"),
    1043: ("Jo?o F?lix", "João Félix"),
    1044: ("Gon?alo Ramos", "Gonçalo Ramos"),
    1069: ("Ch? Adams", "Ché Adams"),
    1072: ("Joan Garc?a", "Joan García"),
    1074: ("Unai Sim?n", "Unai Simón"),
    1075: ("?lex Remiro", "Álex Remiro"),
    1076: ("Pau Cubars?", "Pau Cubarsí"),
    1084: ("Mart?n Zubimendi", "Martín Zubimendi"),
    1089: ("Ferm?n L?pez", "Fermín López"),
    1091: ("?lex Baena", "Álex Baena"),
    1092: ("V?ctor Mu?oz", "Víctor Muñoz"),
    1095: ("Y?remy Pino", "Yéremy Pino"),
    1100: ("Noel T?rnqvist", "Noel Törnqvist"),
    1103: ("Victor Lindel?f", "Victor Lindelöf"),
    1109: ("Jesper Karlstr?m", "Jesper Karlström"),
    1123: ("Viktor Gy?keres", "Viktor Gyökeres"),
    1131: ("Aur?le Amenda", "Aurèle Amenda"),
    1132: ("Eray C?mert", "Eray Cömert"),
    1134: ("Ricardo Rodr?guez", "Ricardo Rodríguez"),
    1144: ("Jo?l Monteiro", "Joël Monteiro"),
    1148: ("Rub?n Vargas", "Rubén Vargas"),
    1151: ("U?urcan ?ak?r", "Uğurcan Çakır"),
    1152: ("Altay Bay?nd?r", "Altay Bayındır"),
    1153: ("Muhammed ?engezer", "Muhammed Şengezer"),
    1154: ("Mert G?nok", "Mert Günok"),
    1157: ("Abd?lkerim Bardakc?", "Abdülkerim Bardakçı"),
    1159: ("Ferdi Kad?o?lu", "Ferdi Kadıoğlu"),
    1160: ("Eren Elmal?", "Eren Elmalı"),
    1161: ("Mustafa Eskihella?", "Mustafa Eskihellaç"),
    1162: ("Zeki ?elik", "Zeki Çelik"),
    1163: ("Mert M?ld?r", "Mert Müldür"),
    1164: ("Hakan ?alhano?lu", "Hakan Çalhanoğlu"),
    1165: ("?smail Y?ksek", "İsmail Yüksek"),
    1167: ("Salih ?zcan", "Salih Özcan"),
    1169: ("Orkun K?k??", "Orkun Kökçü"),
    1170: ("Arda G?ler", "Arda Güler"),
    1171: ("Kenan Y?ld?z", "Kenan Yıldız"),
    1172: ("Bar?? Alper Y?lmaz", "Barış Alper Yılmaz"),
    1173: ("Kerem Akt?rko?lu", "Kerem Aktürkoğlu"),
    1174: ("O?uz Ayd?n", "Oğuz Aydın"),
    1175: ("Yunus Akg?n", "Yunus Akgün"),
    1176: ("?rfan Can Kahveci", "İrfan Can Kahveci"),
    1177: ("Deniz G?l", "Deniz Gül"),
}

for i, line in enumerate(lines, start=1):
    new_line = line
    for old, new in COUNTRY_FIXES:
        new_line = new_line.replace(old, new)
    if i in NAME_FIXES:
        old, new = NAME_FIXES[i]
        if old not in new_line:
            raise ValueError(f"Line {i}: expected fragment {old!r} not found: {new_line!r}")
        new_line = new_line.replace(old, new)
    lines[i - 1] = new_line

remaining = sum(1 for l in lines if "?" in l)
print(f"Remaining lines with '?': {remaining}")

with io.open(path, "w", encoding="utf-8", newline="") as f:
    f.writelines(lines)
